model_store:
  root_directory: "./models"
  default_version_strategy: "latest"

prediction:
  config_path: "../base_config.yaml"
  time_column: "time_stamp"
  status_column: null
  status_mapping: {}
  train_test_column: null
  train_test_mapping: {}
  min_anomaly_length: 18
  critical_event:
    min_consecutive_samples: 18
    min_duration: null
  debug_plots: false
  output_directory: "./artifacts"
  default_asset_name: "{model_name}"
  default_ignore_features: []

security:
  token_ttl_seconds: 900
  tenants:
    sample-org:
      seed_token: "sample-seed-token"
      users:
        analyst: "pbkdf2_sha256$48000$73616d706c652d736565642d746f6b656e$371bcd44be1480cbd06337aea5b38c849e2ac52c2936f7c72960fe5bb48063e5"

cors:
  allow_origins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
