name: Deploy Documentation

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PKG_NAME: energy_fault_detector
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints sphinx-copybutton

      - name: Create VERSION file
        run: echo "${GITHUB_REF##*/}" > "${PKG_NAME}/VERSION"

      - name: Generate API documentation
        run: |
          sphinx-apidoc -o docs "${PKG_NAME}/" --module-first --force --separate --templatedir docs/_templates
          sphinx-build -b html --keep-going docs public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
          force_orphan: true
